#ifndef SEMANTICS_AR_ERRORS_H
#define SEMANTICS_AR_ERRORS_H

typedef enum {
    SEMANTICS_AR_OK = 0,
    SEMANTICS_AR_ERROR_INVALID_PARAM = -1,
    SEMANTICS_AR_ERROR_BUFFER_TOO_SMALL = -2,
    SEMANTICS_AR_ERROR_ALLOC_FAILED = -3,
    SEMANTICS_AR_ERROR_NOT_FOUND = -4,
    SEMANTICS_AR_ERROR_DRIVER_NOT_LOADED = -5,
    SEMANTICS_AR_ERROR_VERSION_MISMATCH = -6,
    SEMANTICS_AR_ERROR_INTERNAL = -100
} semantics_ar_result_t;

#endif
